### ISSUE TITLE
[BUG]Select 选择器 - 可清空单选

### ISSUE THREAD

**Issue by berubou** [eleme/element-angular#135]
![ly gh yyn7bl wkv nq8](https://user-images.githubusercontent.com/14237234/30052704-f1746fec-9258-11e7-8963-7923a990c81e.png)

- 未选择时不应该有清空
- 清空和下拉三角位置不应该重合

**Comment by WittBulter** [comment]
跟进中。
注意选择右边的 label。
下一个 alpha 版本会修复这些问题。

**Comment by WittBulter** [comment]
done
[PR-162](https://github.com/eleme/element-angular/pull/162)
