### ISSUE TITLE
[Feature]Tag 标签

### ISSUE THREAD

**Issue by berubou** [eleme/element-angular#139]
- [ ] 自定义添加标签，获得每次添加时的事件
- [ ] 标签点击/标签移除区分，获得事件
- [ ] 标签文字修改，事件
- [ ] ~~~标签带图标？ （自定义修改/添加~~~
- [ ] ~~~标签拖动排序？~~~

**Comment by WittBulter** [comment]
这个版本会加入。

**Comment by WittBulter** [comment]
移除点击事件已有，文档错误已修复：[PR-161](https://github.com/eleme/element-angular/pull/161)
动态添加标签有点鸡肋，因为 Angular 完全可以动态 watch 一个 tags 数组来达到这一点，先放着看一看，如果后续有人再提再加入。
