### ISSUE TITLE
[Feature]Progress 进度条

### ISSUE THREAD

**Issue by berubou** [eleme/element-angular#140]
- [ ] 进度条文字自定义，func(percent)
- [ ] 颜色自定义
- [ ] ~~~动画？~~~

**Comment by WittBulter** [comment]
下个版本中会加入。

**Comment by WittBulter** [comment]
[pr-160](https://github.com/eleme/element-angular/pull/160)
颜色自定义加入，文字自定义涉及到 filter ，后面再考虑。
