### ISSUE TITLE
响应式表单的支持

### ISSUE THREAD

**Issue by baiyunchen** [eleme/element-angular#173]
在Vue版本的下面提了Issue咨询是否有计划开发angular版本，收到的答复是已经在开发了，激动的我第一时间上来了解。在简单查看了文档之后，发现表单元素这块目前有一些值得改进的地方，具体如下：

- angular表单自身分为模板式表单和响应式表单两套。通过文档来看，目前并不支持响应式表单。
- 另外，我不理解为何要使用觉得使用[(model)]  来代替angular原有的 [(ngModel)]，我觉得这并不是一个最佳实践。
- 我通过文档看到文本框支持maxlength和minlength两个验证用的特性，这里我觉得如果可以通过angular原生的方式来做验证是最好的，因为angular内置了非常强大的验证功能，这点与Vue差距较大。

希望能够继承Vue版本的强大，并结合Angular的优势，做出世界上最好的控件！
感谢你们的辛苦付出！！！

**Comment by WittBulter** [comment]
谢谢你的支持。相应问题请看：
- 要支持响应式表单还有更多工作要做，在未来的版本组件会向 NG 其他的 UI 组件看齐，逐一完善这些。
- 使用 `[(model)]` 最大的原因是，有的组件并非表单，但也需要一个初始值与检测值的变化，这时候我们为这些组件添加了 `[(model)]`，但与 Angular 原生的 `ngModel` 有所区分。在表单组件中为了与其他组件具备相似的 API，也做出了一些取舍，使得整个 `element-angular` 能够保持风格类似的接口。
- Angular 原生验证与示例马上加入。(下个 alpha 或 rc)

希望对你有所帮助。

**Comment by baiyunchen** [comment]
@WittBulter 感谢你的回答。
关于ngModel，我还是希望你们能够内部再讨论一下，因为：
- ngModel本质上与v-model一样，只是个语法糖而已。
- 其他的非原生HTML所具有的表单组件，比如Slider / ColorPicker 这些控件，我倒觉得将他当成表单组件也没有问题，因为他们本身的职责和表单组件一致，都是接受用户的输入。对于日期范围这种可能不止绑定一个值的控件，我个人认为这时候叫model和ngModel都不合适，应该同时绑定两个值,比如start/end才更加容易理解和易用。
- 另外，我觉得既然vue版本的element使用v-model这种原生的指令来实现数据的双向绑定，那angular版本的也应该同理使用原生的[(ngModel)]来实现双向绑定才更加合适，这样来保持各个版本的element的接口相对统一~

原谅我对命名有点强迫症~

**Comment by WittBulter** [comment]
这个问题我也斟酌过，不使用 `ngModel` 出于以下几点原因：

1. `model` 与`ngModel` 一样只是一个语法糖而已，退一步来说，这应当是 `elModel` 而非 `ngModel`。
2. Angular 官方不推荐把 `ngModel` 应用到非表单原生元素或第三方组件上，请参见[文档](https://angular.cn/guide/template-syntax#ngmodel-)：
    > You can't apply [(ngModel)] to a non-form native element or a third-party custom component until you write a suitable value accessor
3. `ngModel` 强依赖于 `FormsModule ` ，而 `FormsModule ` 不总是必须的。
4. 使用 `ng` 前缀会给开发者带来迷惑，当指令越来越多时如何保证哪一个指令是第三方的，哪一个是原生的，哪一个仅仅是被别名代理的。这太难了，甚至会引起各式各样的不可预期的错误。
5. 我们并不需要与 `element-vue` 保持接口的统一，我们希望能够以 NG 的方式实现 UI 效果，同时带有传统 Angular 应用原汁原味的 API 与实现方式，这一点是毋庸置疑的，无论任何框架或语言都会这样做。

这是一个很小的细节，感谢你的建议。
