### ISSUE TITLE
根模块中引入失败

### ISSUE THREAD

**Issue by tc9011** [eleme/element-angular#178]
问题：
在根模块中引入ElModule 失败

版本信息：
    " @ angular/animations": "^4.3.6",
    " @ angular/cdk": "^2.0.0-beta.8",
    " @ angular/cli": "^1.0.0",
    " @ angular/common": "^4.3.6",
    " @ angular/compiler": "^4.3.6",
    " @ angular/compiler-cli": "^4.3.6",
    " @ angular/core": "^4.3.6",
    " @ angular/forms": "^4.3.6",
    " @ angular/http": "^4.3.6",
    " @ angular/material": "^2.0.0-beta.8",
    " @ angular/platform-browser": "^4.3.6",
    " @ angular/platform-browser-dynamic": "^4.3.6",
    " @ angular/platform-server": "^4.3.6",
    " @ angular/router": "^4.3.6",
    " @ ngx-translate/core": "^6.0.1",
    " @ ngx-translate/http-loader": "^1.0.1",
    "angular-in-memory-web-api": "^0.3.2",
    "bootstrap": "^3.3.7",
    "bootstrap-table": "^1.11.2",
    "core-js": "^2.4.1",
    "echarts": "^3.5.3",
    "element-angular": "0.0.4-alpha.3",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "moment": "^2.18.1",
    "ng-zorro-antd": "^0.5.0",
    "ngx-bootstrap": "^1.6.6",
    "primeng": "^4.0.0-rc.3",
    "rxjs": "^5.1.0",
    "typescript": "^2.4.2",
    "zone.js": "^0.8.4"

`app.module.ts`中的代码：
```typescript
import { ElModule } from 'element-angular'
import 'element-theme-default';
//import other modules

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    ElModule.forRoot(),
    BrowserModule,
   //other modules
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

错误信息：
ERROR in /root/Documents/magicCarFinder/magiccarfinderclient/src/app/app.module.ts (13,26): Cannot find module 'element-angular'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve element-angular relative to /root/Documents/magicCarFinder/magiccarfinderclient/src/app/app.module.ts., resolving symbol AppModule in /root/Documents/magicCarFinder/magiccarfinderclient/src/app/app.module.ts, resolving symbol AppModule in /root/Documents/magicCarFinder/magiccarfinderclient/src/app/app.module.ts, resolving symbol AppModule in /root/Documents/magicCarFinder/magiccarfinderclient/src/app/app.module.ts
    at Error (native)
    at syntaxError (/root/Documents/magicCarFinder/magiccarfinderclient/node_modules/@angular/compiler/bundles/compiler.umd.js:1725:34)
    at simplifyInContext (/root/Documents/magicCarFinder/magiccarfinderclient/node_modules/@angular/compiler/bundles/compiler.umd.js:24949:23)
    at StaticReflector.simplify (/root/Documents/magicCarFinder/magiccarfinderclient/node_modules/@angular/compiler/bundles/compiler.umd.js:24961:13)
    at StaticReflector.annotations (/root/Documents/magicCarFinder/magiccarfinderclient/node_modules/@angular/compiler/bundles/compiler.umd.js:24391:41)
    at _getNgModuleMetadata (/root/Documents/magicCarFinder/magiccarfinderclient/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/root/Documents/magicCarFinder/magiccarfinderclient/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/root/Documents/magicCarFinder/magiccarfinderclient/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/root/Documents/magicCarFinder/magiccarfinderclient/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/root/Documents/magicCarFinder/magiccarfinderclient/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/root/Documents/magicCarFinder/magiccarfinderclient/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by WittBulter** [comment]
fixed. #179 

这是一个打包的错误，已经修复。另外使用 `angular-cli` 请注意：
在 `/src/styles.css` 文件中引入样式：
```
@import "~element-theme-default";
```

**Comment by tc9011** [comment]
好的，我更新一下版本，谢谢

**Comment by tc9011** [comment]
好像还有问题。

我项目中使用的是scss，直接`@import "~element-theme-default";`会出现下面错误，是不是还有icon相关的文件要导入：

```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module not found: Error: Can't resolve './fonts/element-icons.ttf?t=1472440741' in '/root/Documents/magicCarFinder/magiccarfinderclient/src'
resolve './fonts/element-icons.ttf?t=1472440741' in '/root/Documents/magicCarFinder/magiccarfinderclient/src'
  using description file: /root/Documents/magicCarFinder/magiccarfinderclient/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /root/Documents/magicCarFinder/magiccarfinderclient/package.json (relative path: ./src)
    using description file: /root/Documents/magicCarFinder/magiccarfinderclient/package.json (relative path: ./src/fonts/element-icons.ttf)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.ttf doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.ttf.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.ttf.js doesn't exist
      as directory
        /root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.ttf doesn't exist
[/root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.ttf]
[/root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.ttf.ts]
[/root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.ttf.js]
[/root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.ttf]
 @ ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss 6:1082-1131
 @ ./src/styles.scss
 @ multi ./src/styles.scss ./node_modules/bootstrap/dist/css/bootstrap.min.css ./node_modules/font-awesome/css/font-awesome.min.css ./node_modules/bootstrap-table/dist/bootstrap-table.min.css ./node_modules/@angular/material/prebuilt-themes/indigo-pink.css ./node_modules/primeng/resources/primeng.min.css ./node_modules/paletxUI/styles/primeng/theme.css ./node_modules/paletxUI/styles/paletxUI.css ./node_modules/paletxUI/styles/fonts/iconfont.css ./node_modules/prismjs/themes/prism-okaidia.css
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module not found: Error: Can't resolve './fonts/element-icons.woff?t=1472440741' in '/root/Documents/magicCarFinder/magiccarfinderclient/src'
resolve './fonts/element-icons.woff?t=1472440741' in '/root/Documents/magicCarFinder/magiccarfinderclient/src'
  using description file: /root/Documents/magicCarFinder/magiccarfinderclient/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /root/Documents/magicCarFinder/magiccarfinderclient/package.json (relative path: ./src)
    using description file: /root/Documents/magicCarFinder/magiccarfinderclient/package.json (relative path: ./src/fonts/element-icons.woff)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.woff doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.woff.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.woff.js doesn't exist
      as directory
        /root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.woff doesn't exist
[/root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.woff]
[/root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.woff.ts]
[/root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.woff.js]
[/root/Documents/magicCarFinder/magiccarfinderclient/src/fonts/element-icons.woff]
 @ ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss 6:1000-1050
 @ ./src/styles.scss
 @ multi ./src/styles.scss ./node_modules/bootstrap/dist/css/bootstrap.min.css ./node_modules/font-awesome/css/font-awesome.min.css ./node_modules/bootstrap-table/dist/bootstrap-table.min.css ./node_modules/@angular/material/prebuilt-themes/indigo-pink.css ./node_modules/primeng/resources/primeng.min.css ./node_modules/paletxUI/styles/primeng/theme.css ./node_modules/paletxUI/styles/paletxUI.css ./node_modules/paletxUI/styles/fonts/iconfont.css ./node_modules/prismjs/themes/prism-okaidia.css
```

如果移除`@import "~element-theme-default";`，编译可以通过，但是页面会报下面错误：

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'model' since it isn't a known property of 'el-input'.
1. If 'el-input' is an Angular component and it has 'model' input, then verify that it is part of this module.
2. If 'el-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("    <px-text-input [(ngModel)]="mapService.basicData.mapid" required></px-text-input>
    <el-input [ERROR ->][model]="input" placeholder="hello"></el-input>
  </div>
```

**Comment by WittBulter** [comment]
第一个报错似乎与你的 sass 配置有关，不能正确的识别 `/src/styles.scss` 的文件，注意你的 `angular-cli` 版本与 scss 语法 (我使用 angular-cli 1.0.4 能够正常工作)。或者尝试使用绝对路径引入，再或者你可以试试在根目录的 `angular-cli.json` 的配置文件中使用绝对路径引入。

第二个 `Can't bind to 'model' since it isn't a known property of 'el-input'` 这个错误应该是模块未被导入，注意看一看你的是不是使用了懒加载 (懒加载需要在自己的模块文件引入) 或路径不对。我怀疑是有缓存相关问题？

先尝试：
1.  `rm -rf node_modules/element-angular node_modules/element-theme-default/`
2. `npm i --save element-angular`

然后考虑以上几个建议。
我尝试使用 `angular-cli`(1.0.4) 从零构建然后安装使用是非常正常的。

**Comment by tc9011** [comment]
感谢，我已经成功引入了element-angular。

具体做法是：
1、在`.angular-cli.json`中：引入css：
```
"styles": [
        "styles.scss",
        "../node_modules/element-theme-default"
      ],
```
2、在`shared.module.ts`中引入组件库:
```
import { NgModule } from '@angular/core';
import { ElModule } from 'element-angular';

const sharedModule = [
  ElModule
];
@NgModule({
  imports: sharedModule,
  declarations: [],
  exports: sharedModule
})
export class SharedModule {}
```
这样在需要用到element-angular组件库的module中导入SharedModule 就行

**Comment by WittBulter** [comment]
@leoshuaige 
其他人有类似问题可见： #228
