### ISSUE TITLE
[BUG] NavMenu导航菜单选项显示问题

### ISSUE THREAD

**Issue by 404157386** [eleme/element-angular#194]
link: https://eleme.github.io/element-angular/#/nav/menu

ng版本:
![image](https://user-images.githubusercontent.com/16297662/30689195-d870ac3a-9ef2-11e7-8e04-af2794f21c51.png)

vue版本的选项是可以显示的:
![image](https://user-images.githubusercontent.com/16297662/30689226-e538810e-9ef2-11e7-94fc-7084e55f6512.png)

查看控制台, html没有把文字渲染上去:
![image](https://user-images.githubusercontent.com/16297662/30689387-616a2c32-9ef3-11e7-937a-4b640dc99ed7.png)

我的浏览器是 Chrome  61.0.3163.79（正式版本） （32 位）

请查看

**Comment by WittBulter** [comment]
这是上次的一个全局改动导致的问题，我会修复它。
谢谢反馈

**Comment by WittBulter** [comment]
#196

**Comment by 404157386** [comment]
请问你修复了的版本 还没发布吧? npm install还是旧的

**Comment by WittBulter** [comment]
是的，稍等

**Comment by WittBulter** [comment]
@404157386 已发布 `0.0.4-beta.1`

**Comment by 404157386** [comment]
@WittBulter 你好，我更新了你发布的package，但是试了几次都compile fail

![tim 20170922153501](https://user-images.githubusercontent.com/16297662/30733929-a8fd30ae-9fab-11e7-878c-bba352f66f7c.jpg)

报这个错：
ERROR in Error encountered resolving symbol values statically. Calling function 'ElModule', function
 calls are not supported. Consider replacing the function or lambda with a reference to an exported
function, resolving symbol AppModule in D:/angular/ng-admin-ui/src/app/app.module.ts, resolving symb
ol AppModule in D:/angular/ng-admin-ui/src/app/app.module.ts

之前一个版本可以正常build的

**Comment by WittBulter** [comment]
我观察一下

**Comment by WittBulter** [comment]
已解决。请更新一下版本。
原因是本地的脚本不是 `ng-cli`，没有注意到错误。

**Comment by 404157386** [comment]
可以了 谢谢 ![image](https://user-images.githubusercontent.com/16297662/30734618-8e75f560-9fae-11e7-9bf0-559294fe530e.png)
