### ISSUE TITLE
el-table 数据无法渲染

### ISSUE THREAD

**Issue by tongjh2** [eleme/element-angular#205]
<el-table [model]="list"> 绑定list后，在ajax请求后，重写list的值，但是表格无法渲染，数据没问题
       this.logService.list({start:0,length:10}).subscribe(res=>{
            this.list = res.aaData;
        })

**Comment by WittBulter** [comment]
我跟进看看

**Comment by WittBulter** [comment]
fixed #206 .
发布了新版本，注意更新。@tongjh2

**Comment by tongjh2** [comment]
升级新版本后完美解决
