### ISSUE TITLE
显示月份如何实现？

### ISSUE THREAD

**Issue by fanslin** [eleme/element-angular#219]
能否实现点击输入框弹出日期选择框（选择框只显示年月，无具体日期），比如点击10月后输入框只显示“2017-10”

![image](https://user-images.githubusercontent.com/15334137/31783032-748d64b6-b4c2-11e7-9428-b63241534f05.png)

**Comment by WittBulter** [comment]
已更新版本，注意更新。

`[hidden-day]` 属性可以隐藏日期，仅显示月份，同时可以通过增加 `[format]` 属性来只获取年与月，如：`[format]="'yyyy年 - MM月'"`。
