### ISSUE TITLE
饿了么的下拉列表 为什么  选择第二个 和 第三个 都会触发时间 选择第一个就不会   

### ISSUE THREAD

**Issue by veryuglyman** [eleme/element-angular#223]
饿了么的下拉列表 为什么  选择第二个 和 第三个 都会触发时间 选择第一个就不会   

`  handle1(a:string):void{
    console.info(a);
    console.info(this.dropList);
  }`

`<el-select (modelChange)="handle1($event)">
              <el-option *ngFor="let item of dropList"
                [label]="item.name"
                [value]="item.id">
              </el-option>
            </el-select>`

`(3) [{…}, {…}, {…}]
0:{id: 0, name: "全部", url: null, description: null}
1:{id: 1, name: "百度推广链接", url: "www.baidu.com", description: "百度推广链接"}
2:{id: 2, name: "QQ推广链接", url: "www.qq.com", description: "QQ推广链接"}
length:3`

**Comment by WittBulter** [comment]
我测试了一下，是没有问题的。

建议你先检查一下代码，或者给我一个线上的代码运行地址看看 (可以上传到[这里](https://jsfiddle.net/))
