### ISSUE TITLE
怎么修改element-angular组件的样式？

### ISSUE THREAD

**Issue by leoshuaige** [eleme/element-angular#228]
饿了么的团队你们好，我想请教一下，怎么修改样式？比如说：我想修改el-alert這個組件的样式，但是我写了没有任何作用？.top-alert .el-alert{
  color: red;
}
类似于这样的写法   除非是改源码里面的样式，但是这样风险比较大，百度也没有方案，还有，你们能否公布一个交流的QQ群，希望大家可以互相帮助，谢谢

**Comment by WittBulter** [comment]
要在 Angular 应用里修改原有的样式是非常简单的，你只需要找到原有的 css类名，写自己的样式覆盖即可：
1. 在控制台找到当前使用组件的样式：
> 可以看到，这里 `el-alert` 组件渲染出来的实际 DOM 元素是 `<div class="el-alert el-alert--success" ...></div>`。
<img width="840" alt="ex1" src="https://user-images.githubusercontent.com/11304944/32143315-80083c76-bce2-11e7-94e3-cd4ddbabd9d2.png">    

2. 选中这个 DOM 元素，在 styles 栏目里察看你需要修改的样式具体属于哪一个：
> 比如这里你想修改背景颜色，背景颜色来自于 `el-alert--success`。
<img width="276" alt="ex2" src="https://user-images.githubusercontent.com/11304944/32143317-8042091a-bce2-11e7-8d6d-6a704caa52aa.png">  

3. 增加样式：
<img width="619" alt="ex3" src="https://user-images.githubusercontent.com/11304944/32143318-80bcef2c-bce2-11e7-990e-eed4dde78deb.png">  

4. 修改视图的打包方式，使当前组件的样式能够覆盖父级的。有关视图封装 (`ViewEncapsulation`) 的几种方式，你可以参考 Angular 的文档或自行搜索。
<img width="622" alt="ex4" src="https://user-images.githubusercontent.com/11304944/32143319-814ec834-bce2-11e7-9d21-a150fb5f0d1d.png">

5. 现在你可以看到已经修改了背景颜色：
<img width="485" alt="ex5" src="https://user-images.githubusercontent.com/11304944/32143382-5d73ba18-bce3-11e7-9b37-0e0afbc08601.png">


### 另一种方式
鉴于前一种方式耦合度太高，所以也可以在在组件上增加 `class` 属性，然后用自己的样式覆盖组件。
有一部分组件是支持添加 `class` 属性，并且会覆盖原有样式，**但不是全部**。  

这里我会在进几日发布一个新版本 (0.2.0)，全部支持样式覆盖的方式：
`<el-alert class="myClass">...</el-alert>`  


最后，目前还没有交流群。不过可以加我的微信 `WittBulter`，拉一个方便交流。

**Comment by leoshuaige** [comment]
好的，非常感謝。

**Comment by WittBulter** [comment]
现在，你可以升级 `0.2.0` 版本，用最新的 `[el-class]` 属性来解决这个问题。
具体你可以参见[文档](https://element-angular.faas.ele.me/guide/directives) 或 PR #229

**Comment by DaiHuaXieHuaKai** [comment]
谢谢
