### ISSUE TITLE
Select希望有个事件

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#233]
比如  onChange

**Comment by WittBulter** [comment]
你指的是 `(modelChange)="handle($event)"` 吗？
可以把 `[(model)]` 拆开为 `[model], (modelChange)`， 这里的事件就是 onChange。

**Comment by hbb520** [comment]
嗯?  Select  组件有这些吗...[https://element-angular.faas.ele.me/form/select](url)

**Comment by WittBulter** [comment]
有的，可见 **基础用法** 中的代码，就是这样写的。
下面的 `Attributes ` 文档没有补充到，这里会加上的。

**Comment by hbb520** [comment]
哦  好吧  现在我意识到了  谢谢了

**Comment by WittBulter** [comment]
文档已完善，见 #239
