### ISSUE TITLE
关于Select 组件的 宽度等

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#235]
希望可以暴露  一个属性(控制下拉面板  的 宽度,和 最大高度 等 )     ;目前 控制下拉面板  的 宽度等于Select input 的宽度  这在有时候很蓝受

**Comment by WittBulter** [comment]
`Select` 组件有一个属性是 `popper-class`，你可以自定义个下拉框的样式，包括宽高。

**Comment by hbb520** [comment]
嗯  谢谢了
