### ISSUE TITLE
Table数据

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#236]
当tableData  数据 属性名 不予 el-table-column 中 model-key="**"  对应时候 页面就会报错吗?  显示我们tableData  获取时各种各样 是否需要自己处理下 来对应model-key="**"  满足不报错吗?

**Comment by WittBulter** [comment]
是这样的。组件需要规则化数据。

这个组件在最初也考虑到为用户排错，但在大多数情况下，会影响带来性能上的损失，实际上不是每个用户都需要深度遍历来核对 `model-key`。
在实际使用过程中，你可以针对自己的数据类型与实际情况，做一些初步的数据格式变换即可。

**Comment by hbb520** [comment]
好吧 你们是权威的    在  数据 不是字符串 的 时候 也会 报错?

**Comment by WittBulter** [comment]
这里有一些设计上的初衷。其实只要 `key` 能够在 `tableData` 找到就不会出错，但这里更严格的要求了 `model-key` 的类型为 `string`。 这里希望能够有统一的风格与数据格式。想象一下过度的自由甚至可以在所有的 `props` 上都用 `any` 来标识，这不是很好的实现方式。有时候自律即自由。 包括其他 `API` 也是如此。

当然，把 `number`、`symbol` 等等用作 `key` 是可行的，如今看来的确可以改动，但还没有到达需要拿出来讨论或非要不可的地步。后面如果有类似的需求会考虑把 `API` 的类型约束做的宽松一些。  

目前来说，只要是不符合 `Attributes` 标识的类型，都会导致错误。所有的类型验证都是严格的。

**Comment by hbb520** [comment]
嗯  谢谢了   很详细,   也许这种严格模式会让使用者离开,但element-angular会更好

**Comment by hbb520** [comment]
嗯  谢谢了
