### ISSUE TITLE
Table 组件数据显示

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#242]
初始化 private  tableData:any[] = []       
  ngOnInit() {
    setTimeout(() => {
      this.tableData= [{
        name: '水爷',
        date: '2017-08-19',
        address: '上海市普陀区金沙江路 1518 弄',
      }];
    }, 2000);
  }
ngOnInit 中更改数据 后 ng-template 中的内容似乎并不生效

**Comment by WittBulter** [comment]
已修复，#243

**Comment by WittBulter** [comment]
尝试下载 `element-angular@0.2.2`
