### ISSUE TITLE
checkbox 错位

### ISSUE THREAD

**Issue by wanghaolu** [eleme/element-angular#250]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  

官网示例中的

Description:
![default](https://user-images.githubusercontent.com/9586655/32223277-abacc3d8-be77-11e7-98b5-710e1c4cc27e.PNG)

**Comment by WittBulter** [comment]
已验证，跟进中

**Comment by WittBulter** [comment]
已修复 #249
