### ISSUE TITLE
select和Cascader下拉列表动画改进

### ISSUE THREAD

**Issue by wanghaolu** [eleme/element-angular#251]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help
不好说是bug还是feature
Version & Environment:  

Description:
下拉列表弹出来的时候感觉是内容现出来后背景动画才滑动出来

**Comment by WittBulter** [comment]
已验证，跟进中

**Comment by WittBulter** [comment]
已修复 #249
