### ISSUE TITLE
版本更新至 0.3.1，同步 Element UI 2.0 后的兼容问题

### ISSUE THREAD

**Issue by WittBulter** [eleme/element-angular#253]
版本更新至 0.3.1 后，同步 Element UI 目前的 2.0 版本，改动较多，具体请参见 [更新日志](https://element-angular.faas.ele.me/guide/log)  。由于框架的理念有所不同，少部分 API 在实现上与 Vue 版本略有出入。  

新版本样式引入方式也有变化，具体请参见[文档](https://element-angular.faas.ele.me)。

对新的主题感兴趣，可以移步 [Elmenet UI 2.0](https://github.com/ElemeFE/element/issues/7755) (Vue)的项目。

**Comment by wanghaolu** [comment]
angular 5.0凌晨发布了，可以考虑升级到5.0了

**Comment by WittBulter** [comment]
正在跟进中

**Comment by WittBulter** [comment]
@wanghaolu 
已兼容 5.0，今天晚一些会发一个新版本
#258
