### ISSUE TITLE
日期选择器删除内容后，日期没有实际清除

### ISSUE THREAD

**Issue by scgy5555** [eleme/element-angular#255]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  
0.3.1

Description:
DatePicker日期选择器
选择日期后，输入框手动删除文字，日期没有清空
picker中changeHandle函数input参数有可能为空

**Comment by WittBulter** [comment]
后面这里的交互会与 Element UI 保持一致：
删除文字之后的 blur 会触发一个 change，如果文字本身没有通过验证或是空文字，会返回上一次的结果不做改变。

跟进中。

**Comment by WittBulter** [comment]
现在清除文字或正确的修改文字后都能触发一次事件，如果当前输入的值不正确，则返回上次的日期。
已修复，#261
