### ISSUE TITLE
table组件 ng-template 很卡

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#256]
Issue Type:
- [x] Bug
Version & Environment:  0.3.1
Description:

   <el-table-column label="操作" width="120" >
      <ng-template #slot let-scope="scope">
           {{scope}} {{scope.rowData}} {{scope.index}}
      </ng-template>
    </el-table-column>

我想 在表格中 template 输出  比如输出 一个图片,等等 像elementUI(vue)那样自定义一个模板 
此时表格的数据加载效率很低

**Comment by hbb520** [comment]
期待table组件 组件更加完善比如 "自定义列模板","多选","展开行"等

**Comment by WittBulter** [comment]
加载效率低指的是？时间花费在 render 上了吗？
贴一下你的 ng-template 内容看看，具体要做那些变更？

**Comment by hbb520** [comment]
<el-table-column label="操作" width="200" >
      <ng-template #slot let-scope="scope">
         {{scope.rowData}}
      </ng-template>
    </el-table-column>


比如我们去到 列的 数据 想对其加工, 而实际上 页面表格中的数据 延迟 一个一个的加载 出来的

**Comment by WittBulter** [comment]
这里不是渲染慢，是没有考虑到需要立刻渲染数据，所有的数据都是鼠标移上去才会发送给 `ng-template`。
现在已经更换了策略。

已解决，#260
