### ISSUE TITLE
Pagination组件jumper样式问题

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#264]
Issue Type:
- [x] Bug
Version & Environment:  
0.4.1
Description:
pagination 组件 的 jumper样式在官网是OK的,但是在我们这里运行是  要 略 大的

**Comment by WittBulter** [comment]
应该是你的全局样式覆盖了。

**Comment by hbb520** [comment]
我一点都没有给全局样式, 更新的0.4.1

**Comment by WittBulter** [comment]
@hbb520 给一个在线的 `demo` 看看，我测试了几个都是正常的

**Comment by hbb520** [comment]
Pagination组件  加号(+)减号(-)按钮 官网是 分开在两侧, 而我下的0.4.1版本 却还是同在右侧

**Comment by WittBulter** [comment]
引入 `styles` 的方式变了，你换了方式吗，注意看文档.

**Comment by hbb520** [comment]
哦 好吧  我始终都没有换 样式 方式
