### ISSUE TITLE
notification组件 官网样式失效

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#269]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  0.4.2
Description:
[https://element-angular.faas.ele.me/notice/notification](url)

**Comment by WittBulter** [comment]
应该是 css 缓存问题，刷新一下或者强制刷新，应该就能解决？

**Comment by hbb520** [comment]
嗯 解决了
