### ISSUE TITLE
Dialog  title

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#273]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  0.4.2
Description:
Dialog  组件 当鼠标滑上时 ,鼠标旁出现title文字,应该是title 属性的设置问题  ,比如跟随鼠标的 "扬州""夏威夷"

[https://element-angular.faas.ele.me/others/dialog](url)
当然  通过 自定义 
<ng-template #title>
 
是没有问题的

**Comment by hbb520** [comment]
[https://element-angular.faas.ele.me/others/dialog](url)

**Comment by WittBulter** [comment]
你只需要把 `title="xxx"` 改写成 `[title]="'xxx'"` 即可避免。
这里因为 `title` 本身也是一个合法属性，它会落在最后生成的标签上，而指定 `[]` 为属性时，则可以避免这一点，因为 Angular 自身的属性会被解析成 ng 开头的新属性：`ng-reflect-title`。

当然这里示例应该避免有异义的写法，我会更新这些示例。
