### ISSUE TITLE
您的tslint.json跟angular自带的不同，这个修改是故意的吗，有什么特别之处吗？

### ISSUE THREAD

**Issue by liepeng328** [eleme/element-angular#280]
您的tslint.json跟angular自带的不同，这个修改是故意的吗，有什么特别之处吗？

**Comment by WittBulter** [comment]
是的。
我所在的项目组使用更多的是无分号与对象行末逗号的风格，当然我自己也非常喜欢这样的风格，所以这里约定了这样。
其次都是一些其他约定，比 `angular/cli` 的更严格，比如强制约束类成员排序，强制约束类型等等，它们在合并 PR 时是必须要求跑通的，希望能够保持更严谨统一的风格。 自律即自由是我的理解。
