### ISSUE TITLE
Select组件清空

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#281]
Issue Type:
- [ ] Bug
- [ ] Feature
- [x] Help

Version & Environment:  0.4.3
Description:
`<el-select [model]="value" placeholder="请选择"`
业务经常需要 清空select的 model 值,而非仅仅通过 组件自带的清空 icon ,
我理想  this.value = null ;可是Select并没有变化,这并没有达到我想要的,这是操作方法错了吗?

**Comment by WittBulter** [comment]
已解决，见 #282   
注意更新至 0.4.4，国内 `npm` 源会延迟
