### ISSUE TITLE
关于table组件template功能

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#283]
Issue Type:
- [x] Bug
- [ ] Feature
- [x] Help
Version & Environment:  0.4.3
Description:
1,table组件template功能:
  要先:
     ` <el-table-column model-key="logo" label="logo" width="140"> </el-table-column>`
  才能保证:
     `<el-table-column model-key="logo" label="logo" width="140">`
        `<ng-template #slot let-scope="scope">`
            `<img src="{{scope.rowData.logo}}" alt="" width="150px" height="100px">`
        ` </ng-template>`
    `</el-table-column>`
   不出错,若果直接写后者,会提示'index'错
2,当我需要两个模板列或者更多个模板列的时候,却总也得不到我想要的..

**Comment by WittBulter** [comment]
跟进中。

**Comment by WittBulter** [comment]
已解决，见 #284   
注意更新版本。
