### ISSUE TITLE
table组件template功能

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#285]
Issue Type:
- [x] Bug
- [ ] Feature
- [x] Help

Version & Environment:  0.4.5
Description:
    只有先  `<el-table-column model-key="logo" label=logo" width="140"></el-table-column>`
   再
    `<el-table-column model-key="logo" label="logo" width="140">`
      `<ng-template #slot let-scope="scope">`
        `{{scope?.rowData}}`
      `</ng-template>`
    `</el-table-column>`
 才能 保证`{{scope?.rowData}}`是有值的
 否则直接写后者是没有值的

**Comment by WittBulter** [comment]
`scope` 表示的是当前行元素
`scope.rowData` 表示的是当前行元素中的数据，比如你的数据是：
```typescript  
tableData: any[] = [{
  name: '重庆小面',
  date: '2017-08-20',
}, {
  name: '海蛎煎',
  date: '2017-08-21',
}]
```   
那么 `rowData` 至少会包含一个 `name` 与 `date`: `{ name: '重庆小面', date: '2017-08-20' }`，表示当前行的数据内容，同时它至少还会有一个 `index` 属性。  

即便所有的元素全部是 `ng-template`，scope 也是有值的，`scope.rowData` 仍旧是一个对象，它至少有一个值 `index` 代表当前点击的行位置。  

我刚刚试了试，是没有问题的，你检查一下代码或者带一个在线 demo 看一下？

**Comment by hbb520** [comment]
不好意思  我刚才表达 有点错    是  {{scope?.rowData?.logo}}  没有值   也就是说当用模板功能时 ,{}{{scope.rowData}}  有其他的,有index   ,就是没有自己

**Comment by WittBulter** [comment]
有本身，是一个 ComponentRef，它的键是随机码。（随机码是因为，在使用模板时，不需要 `model-key="logo"` ，会为模板随机生成一个 ID 作为标识。）
