### ISSUE TITLE
there's a style problem on website: https://element-angular.faas.ele.me/notice/notification

### ISSUE THREAD

**Issue by ivyhaswell** [eleme/element-angular#286]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  

Description:

![1283617264912839812](https://user-images.githubusercontent.com/13186709/32483533-709a2b86-c3d7-11e7-991e-7fdee93c7d0c.png)
![887849028734](https://user-images.githubusercontent.com/13186709/32483732-36e246c0-c3d8-11e7-854c-b9f0cb3c9eb8.png)

if I remove the width attribute in .right class, the noticification component looks ok.

**Comment by WittBulter** [comment]
this is caused by the CSS cache, try: 
- Command + F5
- open browser console, click `Disable cache` and refresh

**Comment by ivyhaswell** [comment]
I find the width atttribute was removed from class right, now it looks ok.

**Comment by ivyhaswell** [comment]
I turn on [Disabled cache], problem occured in another way:
1. press nav-lang to change language
2. click Notification on left nav 
3. click the button and notification showed with width 60px

**Comment by WittBulter** [comment]
seems to be a bug, solving

**Comment by WittBulter** [comment]
Fixed: #288
