### ISSUE TITLE
datepicker 组件bug

### ISSUE THREAD

**Issue by jamessawyer** [eleme/element-angular#287]
Issue Type:
- [ ] Bug
- [x] Feature 
- [ ] Help

Version & Environment:  
node v8.7.0
npm v5.4.2
@angular/cli: 1.4.7

Description:
官网示例上，选择完日期之后，失去焦点会对日期进行格式化操作，但是如果再次focus datepicker的输入框，输入框内部选择的日期会被清空，有没有办法不清空输入框？

查看源码发现调用DateFormat.moment会对一次输入的时间进行格式化，但是第二次聚焦时，因为日期变为一个非法的日期字符串，结果 DateFormat.moment 返回空字符串。

**Comment by WittBulter** [comment]
这是上次改进之后的一个 feature，这样的确不好。
会增加一个属性来控制。跟进中。

**Comment by WittBulter** [comment]
已解决，#289

**Comment by jamessawyer** [comment]
好速度呀，谢谢大佬， 想请问一下添加这个 'change-on-blur' 属性之后，为什么能够解决这个问题呢？我看唯一使用这个属性的地方就是OnInit的时候不调用 tryUpdateText方法

**Comment by WittBulter** [comment]
这里 Blur 不是在 `on-blur` 时候触发的，因为每次点击时间框选择时间时就会触发失焦，所以这里的失焦可以看做是点击组件以外的区域。
这里是在组件以外的区域点击后会触发一次 `tryUpdateText ` (打开 `change-on-blur`)，这里的 `tryUpdateText` 作用是尝试对输入框内的文本做一次解析，同步时间数据。

**Comment by jamessawyer** [comment]
哦哦 谢谢讲解，O(∩_∩)O。期待minDate和maxDate 还有区域选择功能，能透露一下angular这些功能将来会和Vue版同步吗？

**Comment by WittBulter** [comment]
会同步的。
