### ISSUE TITLE
Navbar RWD 

### ISSUE THREAD

**Issue by hedonghui** [eleme/element-angular#292]
Issue Type:
- [x] Feature

**Current behavior**
We can use menu to do the navbar as in layout demo.
Navbar no RWD yet.

**Expected behavior**

![](https://user-images.githubusercontent.com/18013815/30526597-cf71e8c4-9c4f-11e7-939c-925f51d53fe0.png)

![](https://user-images.githubusercontent.com/18013815/30526598-d4903536-9c4f-11e7-84d2-fc8c6fac8965.png)

Version & Environment:  

Description:

**Comment by WittBulter** [comment]
we don't have this plan for the time being, PWD means more rigorous grid system design, maybe it will be added in the future, but not now.
if you're using element-angular, this rep may help to you [ng2-responsive](https://github.com/ManuCutillas/ng2-responsive)
