### ISSUE TITLE
angular5报错 index 报错

### ISSUE THREAD

**Issue by hbb520** [eleme/element-angular#293]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  0.4.5
Description: 
项目报错,运行不了,报错提示
ERROR in ./node_modules/element-angular/index.ts
Module build failed: Error: F:\wrok2\goods-web\node_modules\element-angular\index.ts is not part of the compilation output. Please check the other error messages for details.
at AngularCompilerPlugin.getCompiledFile (F:\wrok2\goods-web\node_modules@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
at plugin.done.then (F:\wrok2\goods-web\node_modules@ngtools\webpack\src\loader.js:467:39)
at process._tickCallback (internal/process/next_tick.js:109:7)
@ ./src/app/app.module.ts 22:0-43
@ ./src/main.ts
@ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by WittBulter** [comment]
在 Angular 5 下测试是通过的，@angular/cli 项目也是通过的。
请提供更多信息或线上示例。

**Comment by Herryjoeson** [comment]
我也是在5.0下来启动开发服务器报错的

**Comment by WittBulter** [comment]
@Herryjoeson 
请问是 windows 吗？
着急可以加群
![wechatimg50](https://user-images.githubusercontent.com/11304944/32941145-c5cac80a-cbbf-11e7-9d7b-5b568e42ade2.jpeg)

**Comment by WittBulter** [comment]
这看起来是 `@angular/cli` 的问题，你可以在这个 issue 查看跟进情况 [8284](https://github.com/angular/angular-cli/issues/8284)
