### ISSUE TITLE
import ElModule is undefined

### ISSUE THREAD

**Issue by xiaohuoni** [eleme/element-angular#296]
Issue Type:
- [ ] Bug
- [ ] Feature
- [x] Help

Version & Environment:  
Angular CLI: 1.5.3
Node: 8.9.1
OS: win32 x64
Angular: 5.0.2
dev：vscode

Description:

# install cli
npm install -g @angular/cli

# init project
ng new YOUR-PROJECT-NAME --style=scss
cd YOUR-PROJECT-NAME

# install element-angular
npm i --save element-angular

# run
ng server

import { ElModule } from 'element-angular'
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
console.log(ElModule) //undefined

**Comment by WittBulter** [comment]
append this scripts to your `tsconfig.json`: 
```json
"include": [
    "src/**/*",
    "node_modules/element-angular/index.ts"
  ]
```  

my `tsconfig.json`:  
```json  
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include": [
    "src/**/*",
    "node_modules/element-angular/index.ts"
  ]
}

```

**Comment by xiaohuoni** [comment]
ERROR in ./node_modules/_element-angular@0.4.5@element-angular/index.ts
Module build failed: Error: D:\oni-td\node_modules\_element-angular@0.4.5@element-angular\index.ts is not part of the compilation. Please make sure it is in your tsconfig via the
'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (D:\oni-td\node_modules\_@ngtools_webpack@1.8.3@@ngtools\webpack\src\angular_compiler_plugin.js:619:23)
    at plugin.done.then (D:\oni-td\node_modules\_@ngtools_webpack@1.8.3@@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ ./src/app/app.module.ts 7:0-43
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by WittBulter** [comment]
it's like @angular/cli's error, as far as i know this mistake will only happen in windows.
are you using CNPM? try changing to NPM and reload project.

if you still meet this error, try  roll back to the angular@5.0.rc or angular@4.x.  

this is our wechat chat room:  

![33](https://user-images.githubusercontent.com/11304944/33133640-5d3366fe-cfd8-11e7-9f1d-79250e726d97.jpeg)

**Comment by WittBulter** [comment]
solved.
