### ISSUE TITLE
NavMenu route 

### ISSUE THREAD

**Issue by lyc152** [eleme/element-angular#300]
Issue Type:
- [ ] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  

0.4.7

Description:

 请问下 当前版本的 NavMenu 怎么和 route 配合使用，发现 el-menu-item 不能用 click 事件, routeLink 也没效果, el-menu 倒是可以 click ，但是不知道怎么传入 current Index, 麻烦看下怎么解决，谢谢！

**Comment by WittBulter** [comment]
`[(model)]` 可以拆解成 `[model]` 与 `(modelChange)` 。通过 `modelChange` 你可以绑定一个函数，参数为点击的 index 值。
或者你可以直接使用双向绑定，但是获的 `push` 的效果可能需要 `onChange` 。

```html
<el-menu theme="dark" [model]="0" (modelChange)="handle($event)">
....
</el-menu>
```    
```ts  
// in Component  
handle(index: number): void {
// 点击了第 index 个
}
```
