### ISSUE TITLE
Element Angular 发布 0.5.0，已支持响应式表单

### ISSUE THREAD

**Issue by WittBulter** [eleme/element-angular#305]
Issue Type:
- [x] Feature

Description:
element-angular 已经发布 0.5.0-beta.1 版本，目前已支持 Angular 的响应式编程风格表单，同时修复了一些表单系统存在的样式问题。可以参见[表单文档](https://element-angular.faas.ele.me/form/form)   

@m17319325007   
@XGHeaven  
@baiyunchen

**Comment by zhangchangzhao** [comment]
维特大佬我来瞻仰一波。

**Comment by xiaomoinfo** [comment]
被大佬follow，心里有点慌。

**Comment by baiyunchen** [comment]
前来支持~

**Comment by CHJ1993** [comment]
日期选择组件 能否附加个选择到时间的 ?

**Comment by WittBulter** [comment]
@CHJ1993 是时间选择器吗，还是按选择时间段？

**Comment by CHJ1993** [comment]
时间选择器，还有比如 一个组建就可以选择  2017-12-19 14:15 这种时间  日期和时间组合的组件

**Comment by CHJ1993** [comment]
https://www.primefaces.org/primeng/#/calendar 比如这个 里面的Time 例子

**Comment by WittBulter** [comment]
@CHJ1993 
下个 Feature 版本增加。

**Comment by CHJ1993** [comment]
占楼观望

**Comment by swliu920322** [comment]
之前根据你们vue版本做了angular的form，async-validator挺好用的，怎么你们舍弃了

**Comment by WittBulter** [comment]
@swliu920322 Angular 当然是用原生紧密结合的响应式范式表单，相比之下，async-validator 就太弱了.....

**Comment by swliu920322** [comment]
就是觉得使用起来好像比之前vue版本的要麻烦一点
