### ISSUE TITLE
ng build打包压缩混淆代码报错

### ISSUE THREAD

**Issue by biezhenyu** [eleme/element-angular#306]
Issue Type:
- [ ] Bug
- [ ] Feature
- [x] Help

Version & Environment:  
0.5.0-beta.1

Description:
ERROR in vendor.904d04559cb6076a05ce.bundle.js from UglifyJs
Unexpected character '`' [vendor.904d04559cb6076a05ce.bundle.js:87,101]

**Comment by biezhenyu** [comment]
xxx

**Comment by WittBulter** [comment]
你好，我在各类环境下测试后均没有问题，包括 eject 与 angular/cli 。
而且很多人正在使用也未发生过这类问题。你可以先检查一下自己的代码，尝试移除 Element Angular 后再尝试。我猜测可能是你的模板剁了一个 '`'。
