### ISSUE TITLE
关于table中的表头不能居中的问题

### ISSUE THREAD

**Issue by leoshuaige** [eleme/element-angular#307]
我用自定义的 [el-class]自定义样式，没有起作用。而且这个自定义的样式，一点都不好用，压根没有效果，还有，table是可以左右滑动的，但是表头不能跟着左右滑动，貌似表头是固定死的？怎么解决这个bug？求大神指点

![image](https://user-images.githubusercontent.com/26239202/33827913-f94e21a2-dea4-11e7-96de-df749b20ac4e.png)

**Comment by leoshuaige** [comment]
不好意思，图片重复提交了、。

**Comment by WittBulter** [comment]
fixed #312
