### ISSUE TITLE
table表格循环的问题

### ISSUE THREAD

**Issue by leoshuaige** [eleme/element-angular#308]
直接上图片吧。
![111](https://user-images.githubusercontent.com/26239202/33833618-2bd7c6b2-debb-11e7-8ab0-104b7fb69b31.png)

**Comment by leoshuaige** [comment]
![Uploading 222.png…]()
![111](https://user-images.githubusercontent.com/26239202/33833578-0418b802-debb-11e7-9f02-c28075e3cb62.png)

**Comment by leoshuaige** [comment]
额 网络太卡了，所以分开上传

**Comment by leoshuaige** [comment]
一次传2个图片报错，分开上传
![222](https://user-images.githubusercontent.com/26239202/33833835-eb169c9c-debb-11e7-9660-cc4b300852bd.png)

**Comment by WittBulter** [comment]
你的 `scope` 会把上下文传递给 `handle` 函数。
 不能对对象进行取值，在 column 中，因为在遍历是无法知道是 `a.b` 还是 `a[b]`，它会被认作是一个字符串。

**Comment by leoshuaige** [comment]
那有没有办法解决呢？vue是可以的

**Comment by WittBulter** [comment]
这里我推荐你把这个对象简化一下。目前你可以先跳过这里或使用一些取巧的办法。

因为设置一个复杂的动态的键去对象取值需要做一些判断和排错，这和 Angular 的风格也不符合。你应该也注意到了，很少会使用动态键取值。
当然这个加入这个功能也不困难，但相对的加重了普通表格的负担（因为无论是不是普通的键，总是要先运行一遍排错），未来这里计划增加一个属性来决定是否要深度解析。下个 feature 版本可以加入。
