### ISSUE TITLE
ng build --pord aot error!!!

### ISSUE THREAD

**Issue by lan-xue-xing** [eleme/element-angular#316]
Issue Type:
- [ true] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  
    ```
"@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "element-angular": "^0.5.0-beta.1"
```

Description:
ng build --pord aot error!!!
Unexpected token: name (ElMenuItemGroup) [vendor.abb2fcd58dce3f28c38d.bundle.js:309,6]

**Comment by WittBulter** [comment]
I tested the module package, looking good. can you upgrade element-angular to `0.5.0-beta.2` and try again ? if there still throw error, you need provide more information about your project, or add an online project.

**Comment by lan-xue-xing** [comment]
I upgrade element-angular to 0.5.0-beta.2 and try again, but there's still the same error.
`ERROR in vendor.57a92c7c319f3dce0206.bundle.js from UglifyJs
Unexpected token: name (ElMenuItemGroup) [vendor.57a92c7c319f3dce0206.bundle.js:309,6]`
I built a new project, then install element-angular lib and try again, but it still very disappointed.
My package.json configuration is as follows
`"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "element-angular": "^0.5.0-beta.2",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.2",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }`

`node 7.1.0 npm 5.5.1 @angular/cli: 1.4.2`

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { ElModule } from 'element-angular';
import 'element-angular/theme/index.css';

in app.module.ts
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    ElModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

in app.component.html
`<div style="text-align:center">
    <h1>
        Welcome to {{title}}!
    </h1>
    <img width="300" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<el-badge [model]="12" class="item">
    <el-button size="small">评论</el-button>
</el-badge>

<el-badge [model]="3" class="item">
    <el-button size="small">回复</el-button>
</el-badge>`

final in src/styles.css

`@import "~element-angular/theme/index.css"`

Do you have any good suggestions?

**Comment by WittBulter** [comment]
i will follow up

**Comment by WittBulter** [comment]
you're sure `app.module.ts` is the content of your file and watched the tutorials carefully? there are many grammatical mistakes in it. 
i compiled with the version you specified, no any errors. I hope you can give me an online example about your project.

**Comment by lan-xue-xing** [comment]
I'm sorry, I had some negligence when I was edited, I uploaded an example in GitHub, `https://github.com/lan-xue-xing/elTest.git`

**Comment by WittBulter** [comment]
this error may be caused by the `UglifyJs` library, but i'm not sure. 

i found some answer from angular library issues,  don't use es6+ features can resolve this problem, or use `github:mishoo/UglifyJS2#harmony` replace native library. 

in the same way, you can use es5 bundle:
```
import * as ElementAngular from 'element-angular/bundle/element-angular.js';
// ... 
ElementAngular.ElModule.forRoot()
```  

these are not the best solutions, i suggest upgrade @angular/cli to 1.5.0+, this will resolve all errors.

**Comment by WittBulter** [comment]
i hope these will help you, thanks for you feedback.

**Comment by lan-xue-xing** [comment]
Thank you for your reply, I upgraded @angular/cli to 1.5.2 has been resolve.
