### ISSUE TITLE
el-menu 主题色支持dark吗？

### ISSUE THREAD

**Issue by SunXingZ** [eleme/element-angular#319]
el-menu 主题设置为dark无效！样式表里根本没有el-menu--dark的样式

**Comment by WittBulter** [comment]
看起来像是一个 bug，跟进中

**Comment by WittBulter** [comment]
`dark` 的主题是 Element UI 1.x 的设计，更新至 2.0 版本后这个设计取消了，但 element-angular 未更新菜单导致了这个错误。
现在增加了更加详细的颜色配置 (#324 )，今天的 patch 版本 `0.5.0-beta.3` 会发布。
