### ISSUE TITLE
el-tab is  not in latest version

### ISSUE THREAD

**Issue by zhangzequan** [eleme/element-angular#320]
Issue Type:
- [ ] Bug
- [x] Feature
- [ ] Help

Version & Environment:  

Description:

**Comment by zhangzequan** [comment]
el-tab is not supported in the latest version

**Comment by WittBulter** [comment]
can you provide your version and error details ?
i cant repeat this mistake, need more details.

**Comment by WittBulter** [comment]
the problem is out of date, closed.
