### ISSUE TITLE
[Feature] NavMenu 导航菜单选中子item，父item同样设置选中状态

### ISSUE THREAD

**Issue by JerryMissTom** [eleme/element-angular#321]
Issue Type:
- [ ] Bug
- [x] Feature
- [ ] Help

Version & Environment:  
Element-Angular: 0.5.0

Description:
NavMenu 导航菜单选中子item，父item未设置选中状态，子item 隐藏，无法得知哪个item被选中，需要找寻，不是很友好。

**Comment by WittBulter** [comment]
的确是这样。
下个小版本会优化这个问题。

**Comment by JerryMissTom** [comment]
good work

**Comment by WittBulter** [comment]
已加入这个特性，详情请看 #324 。今天会更新一个 patch 版本 `0.5.0-beta.2`。
