### ISSUE TITLE
表格model-key为什么只支持string类型？

### ISSUE THREAD

**Issue by SunXingZ** [eleme/element-angular#322]
如题： 表格model-key为什么只支持string类型？不觉得很不方便吗？不知道你们咋想的！

**Comment by WittBulter** [comment]
哪里不方便，你需要其他类型作为键吗，举个实际场景的例子看看。

**Comment by SunXingZ** [comment]
@WittBulter 例如现在有一个管理员列表，我需要绑定管理员的年龄字段，该字段在后台设置的是number类型，我前端绑定的时候就会报错了，所以后台所有的字段类型都必须为string类型的。你觉得这样方便吗？还是说有我不知道的操作？

**Comment by WittBulter** [comment]
你可以在绑定的时候把它转化一下类型就可以了，在前端系统里面，完全不必因为这些小问题舍近求远，要求更改接口或数据源。
比如在模板中：`<xxxx  [someKey]=" +key ">` 可以把 key 转化为数字。同理，`'' + key` / `${key}` / `key.toString()` / `key | stringPipe` / `someFilter(key)` 等等都可以把一个值转化为字符串。

**Comment by SunXingZ** [comment]
`<el-table-column [model-key]="Created_Date.toString()" label="添加日期"></el-table-column>`
这种操作吗？

**Comment by SunXingZ** [comment]
@WittBulter `<el-table-column [model-key]="Created_Date.toString()" label="添加日期"></el-table-column>`
这种操作吗？

**Comment by XGHeaven** [comment]
@SunXingZ 我替维特大佬解释一下吧。
首先 `model-key` 需要填入的是你要显示的那个属性所对应的 `key` 值。比如说你现在有一个数组。
```
[
  {age: 10, name: 'bar'},
  {age: 20, name: 'foo'},
]
```

如果你想显示年龄，那么你可以让 `model-key` 为 `age` 即可。
```
<el-table-column model-key="age"></el-table-column>
```
那么他将会自动显示 `key` 为 `age` 的值。

所以说，我感觉你可能是理解错文档的意思了。值什么都可以的，但是 `key` 就应该是字符串类型的（别太抠字眼，明白就好）。

其次建议你认真的阅读一下文档，还有就是多去了解一下 Github
> // 删除问题是什么👻

**Comment by SunXingZ** [comment]
@XGHeaven 感谢你的解答、我尝试过你的方法，但是控制台依然报错。

这是我的html
`<el-table-column model-key="number" label="用户编号"></el-table-column>`

这是我的ts
` [
        {
          number: 1,
          name: "水爷",
          date: "2017-08-19",
          address: "上海市普陀区金沙江路 1518 弄",
          status: "在线"
        },
        {
          number: 2,
          name: "水爷",
          date: "2017-08-20",
          address: "上海市普陀区金沙江路 1518 弄",
          status: "离线"
        }
      ];`

控制台报错：`ERROR TypeError: templateRef.createEmbeddedView is not a function`

**Comment by XGHeaven** [comment]
@SunXingZ 
我测试了你的例子，确实会有这样的问题。
我之前理解错你的意思了，可能是你的标题描述的有问题，导致理解错意思。
你想表达的是为啥 value 只支持 string，而不是 key。

fixing

**Comment by XGHeaven** [comment]
@SunXingZ 问题已经修复
