### ISSUE TITLE
为什么删除我的问题？

### ISSUE THREAD

**Issue by SunXingZ** [eleme/element-angular#323]
为什么删除我的问题？

**Comment by WittBulter** [comment]
没有删除。
已解决并且与组件本身无关，同时也为你提供了解决方案，所以关闭。
如果你基础的问题不理解，可以先学习 TypeScript 与 Angular 。
谢谢你的关注。

**Comment by SunXingZ** [comment]
@WittBulter 感谢你的耐心回答、并不是我基础问题不理解、我也不是第一次使用angular和typescript进行开发、用过的很多插件和框架的接口并没有设计成单一类型来确保稳定性。
