### ISSUE TITLE
什么时候能支持360浏览器和IE

### ISSUE THREAD

**Issue by jellyPotato** [eleme/element-angular#332]
Issue Type:
- [ ] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  

Description:

什么时候能支持360浏览器和IE

**Comment by WittBulter** [comment]
这个和组件关系并不大，Element Angular 只用了 Angular 中标准的 API，自己并没有额外的扩充语法，支持到多少浏览器是看你的项目整体的兼容度。
具体你可以阅读有关 Angular  polyfill 的知识，一般 cli 创建的项目都有 polyfill 文件，用于填平一些浏览器差异与兼容过时的浏览器。至于 IE，你可以看看官方文档如何让你的项目兼容到更低版本。
谢谢你的关注与支持。
