### ISSUE TITLE
表格的一些问题

### ISSUE THREAD

**Issue by Cyclone77** [eleme/element-angular#333]
``` html
<el-table [model]="tableData" [border]="true" [scroll-x]="false">
    <el-table-column model-key="name" label="姓名" width="140">
    </el-table-column>
    <el-table-column model-key="date" label="日期" width="140">
    </el-table-column>
    <el-table-column model-key="address" label="地址">
    </el-table-column>
</el-table>
```

> 最后一列未设置宽度

``` javascript
//  in component
tableData: any[] = [{
    name: '水爷',
    date: '2017-08-19',
    address: '上海市普陀区金沙江路 1518 弄',
  }, {
    name: '水爷',
    date: '2017-08-20',
    address: '上海市普陀区金沙江路 1518 弄',
  }, {
    name: '水爷',
    date: '2017-08-21',
    address: '上海市普陀区金沙江路 1518 弄',
  }, {
    name: '水爷',
    date: '2017-08-22',
    address: '上海市普陀区金沙江路 1510 弄',
  }];
```
![scroll](https://user-images.githubusercontent.com/10395760/34472951-4cd010fc-efa7-11e7-8305-ea6b5fe73b89.png)

**2018年1月2日 10:48:51 补充：**
行的scope上rowData不存在当前列的数据，比如给数据列添加ng-template，无法获取当前列的数据。
例如：把姓名变成a链接或者input

**Comment by WittBulter** [comment]
1. 未设置宽度会自动分配，可能会出现滚动条，如果希望不需要滚动条，就全部设置自己的宽度。
2. 是的，只能获得当前行的数据。后面会考虑列的数据。

谢谢你的关注和反馈。

**Comment by Cyclone77** [comment]
@WittBulter

**Comment by WittBulter** [comment]
行的信息当然可以获得，通过 `{{ scope.rowData.{key} }}` 获得。
<img width="456" alt="wx20180103-215312 2x" src="https://user-images.githubusercontent.com/11304944/34523040-a49873ae-f0d0-11e7-953a-2fbd2b1e0fd1.png">
<img width="172" alt="wx20180103-215326 2x" src="https://user-images.githubusercontent.com/11304944/34523047-aa0a4ab0-f0d0-11e7-8438-312fa6b8a9de.png">
如果不能获取当前行的值，可以看一下错误再跟进。（列的信息没有保存）

另外 tree 还在设计中， 近期可能不会发布新版本。（下个版本包括 Tree 组件与 Time 组件，不包括 Bug 修复的 patch 版本）

**Comment by Cyclone77** [comment]
你在非当前列`lable="操作"`获取别的列的值 `model-key="name"`可以用scope.rowData.name，你在 `model-key="name"`列试试scope.rowData.name并没有值。

**Comment by WittBulter** [comment]
实际上如果子元素是 `ng-template` 时，会忽略 `model-key` 为当前列创建一个随机 key，所以是当前列 (name) 是不存在的，所以无法获取。

**Comment by Cyclone77** [comment]
@WittBulter  打扰一下， 表格异步后无法绑定数据？

**Comment by WittBulter** [comment]
这个问题已经解决了。@Cyclone77

**Comment by Cyclone77** [comment]
谢谢
