### ISSUE TITLE
navmenu 两级菜单 如何默认展开

### ISSUE THREAD

**Issue by chenbobaoge** [eleme/element-angular#334]
Issue Type:
- [x] Bug
- [ ] Feature
- [ ] Help

Version & Environment:  

Description:

两级菜单
1
1-1
1-2
2
2-1
2-2

如何在第一次打开时保持菜单一打开

**Comment by WittBulter** [comment]
目前还没有参数来保证子级菜单的状态，不过子项选中状态可以通过 `model` 设置。

**Comment by chenbobaoge** [comment]
ok   我试试
