### ISSUE TITLE
when click "Slider" , its change event can not be triggered.

### ISSUE THREAD

**Issue by KunerRick** [eleme/element-angular#335]
Issue Type:
- [ ] Bug

Version & Environment:  
Version: 0.5.0-beta.5

Description:
when click "Slider" , its change event can not be triggered.You known, we do not always drag the slider, we may click it, but its change event can not be triggered.

**Comment by WittBulter** [comment]
thanks for your feedback, this like a error, i will fix it.

**Comment by WittBulter** [comment]
fixed, upgrade version plz.
