### ISSUE TITLE
Upload component request body settings and set file upload domain.

### ISSUE THREAD

**Issue by lan-xue-xing** [eleme/element-angular#336]
Issue Type:
-  Help

Description:   Excuse me, the upload component can provide the default request body parameters to modify the file upload and set the file upload domain name? you know this often needed.

**Comment by WittBulter** [comment]
can you describe it in more detail?

**Comment by lan-xue-xing** [comment]
In the case of uploading attachments, some additional parameters may need to be carried because of some needs. The post method of the upload component can provide body parameter setting method or attributes (such as formData, default is {})? And set the file upload domain name, the default value is file, I want to modify this field.

**Comment by WittBulter** [comment]
this feature may change a lot of API, the api design will not be changed in the short term, however, this is a good proposal, we will plan this in the future, but not now. 🤒

**Comment by lan-xue-xing** [comment]
thank you very much, looking forward to new features.
