### ISSUE TITLE
Dropdown 下拉菜单“文字和箭头”的颜色如何更改

### ISSUE THREAD

**Issue by Cyclone77** [eleme/element-angular#338]
Issue Type:
- [ ] Help

Version & Environment:  
文字用可以放在span中修改颜色，但是那个下拉的小箭头怎么更改颜色。
不能全局修改，虽然可以在angular cli 根目录下style.css 修改，但是不能这样做。

**Comment by WittBulter** [comment]
class 是 `el-icon-caret-bottom el-icon--right`
参考 [class directive](https://element-angular.faas.ele.me/guide/directives) 与 #228 ，为元素增加一个自己的类名，然后覆盖原有的样式。

**Comment by Cyclone77** [comment]
感谢
